apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
